version: '2'

services:
  web:
    build: .
    links:
      - mysql
    volumes_from:
      - web-data
    volumes:
      - /home/ghjnut/projects/docker/beets/data/clean:/media:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
  web-data:
    image: debian:jessie
    volumes:
      - ./data/ampache/config:/var/www/html/config
      - ./data/ampache/themes:/var/www/html/themes

  mysql:
    image: mysql:5.5
    volumes_from:
      - mysql-data
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=test
  mysql-data:
    image: debian:jessie
    volumes:
      - ./data/mysql/:/var/lib/mysql
